name: Build Apk

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 10    

    steps:
    - uses: actions/checkout@v4

    - name: Setup Keystore File
      run: |
        echo "${{secrets.ANDROID_KEYSTORE_FILE}}" > appambit.keystore.asc
        gpg -d --passphrase "${{secrets.ANDROID_KEYSTORE_PASSWORD_GPG}}" --batch appambit.keystore.asc > appambit.keystore
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '17'

    - name: Install Android Workload
      run: dotnet workload install maui-android

    - name: Restore Android dependencies
      run: dotnet restore -p:TargetFramework=net8.0-android
      working-directory: ./AppAmbitTestingApp

    - name: Build Android
      run: dotnet build -c:Release -f:net8.0-android /p:AndroidSigningKeyStore=../appambit.keystore /p:AndroidSigningKeyAlias=kavaup /p:AndroidSigningKeyPass="${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" /p:AndroidSigningStorePass="${{ secrets.ANDROID_KEYSTORE_PASSWORD_ALIAS }}" --no-restore
      working-directory: ./AppAmbitTestingApp

    - name: Upload Android Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: android-apk
        path: ./AppAmbitTestingApp/bin/Release/net8.0-android/**/*.apk
